import { authenticator } from 'otplib';
import chalk from 'chalk';
import { resolve, jsonDb, datetime, filenamify, prompt, confirm, notify, html_game_list } from './src/util.js';
import { cfg } from './src/config.js';
import { launchBrowser } from './src/browser.js';

const screenshot = (...a) => resolve(cfg.dir.screenshots, 'prime-gaming', ...a);

const URL_CLAIM = 'https://luna.amazon.com/claims';

console.log(datetime(), 'started checking prime-gaming');

const db = await jsonDb('prime-gaming.json', {});

const { context, page } = await launchBrowser(cfg.dir.browser, { recordPrefix: 'pg' });

const notify_games = [];
let user;

try {
  await page.goto(URL_CLAIM, { waitUntil: 'domcontentloaded' });
  await Promise.any(['button:has-text("Sign in")', '[data-a-target="user-dropdown-first-name-text"]'].map(s => page.waitForSelector(s)));
  page.click('[aria-label="Cookies usage disclaimer banner"] button:has-text("Accept Cookies")').catch(_ => { });
  while (await page.locator('button:has-text("Sign in")').count() > 0) {
    console.error('Not signed in anymore.');
    await page.click('button:has-text("Sign in")');
    if (!cfg.debug) context.setDefaultTimeout(cfg.login_timeout);
    console.info(`Login timeout is ${cfg.login_timeout / 1000} seconds!`);
    if (cfg.pg_email && cfg.pg_password) console.info('Using email and password from environment.');
    else console.info('Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).');
    const email = cfg.pg_email || await prompt({ message: 'Enter email' });
    const password = email && (cfg.pg_password || await prompt({ type: 'password', message: 'Enter password' }));
    if (email && password) {
      await page.fill('[name=email]', email);
      await page.click('input[type="submit"]');
      await page.waitForTimeout(3000);
      const pwField = page.locator('#ap_password, input[type="password"]:not(#ap-credential-autofill-hint)').first();
      await pwField.waitFor({ state: 'visible', timeout: cfg.login_timeout });
      await pwField.fill(password);
      await page.click('input[type="submit"]');
      page.waitForURL('**/ap/signin**').then(async () => {
        const error = await page.locator('.a-alert-content').first().innerText();
        if (!error.trim().length) return;
        console.error('Login error:', error);
        await notify(`prime-gaming: login: ${error}`);
        await context.close();
        process.exit(1);
      });
      page.waitForURL('**/ap/mfa**').then(async () => {
        console.log('Two-Step Verification - enter the One Time Password (OTP), e.g. generated by your Authenticator App');
        await page.check('[name=rememberDevice]');
        const otp = cfg.pg_otpkey && authenticator.generate(cfg.pg_otpkey) || await prompt({ type: 'text', message: 'Enter two-factor sign in code', validate: n => n.toString().length == 6 || 'The code must be 6 digits!' });
        await page.locator('input[name=otpCode]').pressSequentially(otp.toString());
        await page.click('input[type="submit"]');
      }).catch(_ => { });
      page.waitForURL('**/ap/cvf/**').then(async () => {
        console.log('Amazon Customer Verification - a verification code has been sent to your email or phone.');
        await page.screenshot({ path: screenshot('cvf-verification.png') });
        const pageText = await page.locator('body').innerText();
        console.log('Verification page info:', pageText.substring(0, 300));
        const otp = await prompt({ type: 'text', message: 'Enter Amazon verification code' });
        if (otp) {
          const otpInput = page.locator('input[name="code"], input[type="text"]').first();
          await otpInput.fill(otp.toString());
          await page.click('input[type="submit"], button[type="submit"]');
        }
      }).catch(_ => { });
    } else {
      console.log('Waiting for you to login in the browser.');
      await notify('prime-gaming: no longer signed in and not enough options set for automatic login.');
      if (cfg.headless) {
        console.log('Run `SHOW=1 node prime-gaming` to login in the opened browser.');
        await context.close();
        process.exit(1);
      }
    }
    await page.waitForURL(u => u.href.startsWith('https://luna.amazon.com/'), { timeout: cfg.login_timeout });
    if (!cfg.debug) context.setDefaultTimeout(cfg.timeout);
  }
  user = await page.locator('[data-a-target="user-dropdown-first-name-text"]').first().innerText();
  console.log(`Signed in as ${user}`);
  db.data[user] ||= {};

  if (await page.getByRole('button', { name: 'Try Prime' }).count()) {
    console.error('User is currently not an Amazon Prime member, so no games to claim. Exit!');
    await context.close();
    process.exit(1);
  }

  const waitUntilStable = async (f, act) => {
    let v;
    while (true) {
      const v2 = await f();
      console.log('waitUntilStable', v2);
      if (v == v2) break;
      v = v2;
      await act();
    }
  };
  const scrollUntilStable = async f => await waitUntilStable(f, async () => {
    await page.keyboard.press('PageDown');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(3000);
    await page.keyboard.press('PageDown');
    await page.waitForTimeout(3000);
  });

  await page.click('button[data-type="Game"]');
  const games = page.locator('div[data-a-target="offer-list-FGWP_FULL"]');
  await games.waitFor();
  await scrollUntilStable(() => page.evaluate(() => document.querySelector('.tw-full-width').scrollHeight));
  console.log('Number of already claimed games (total):', await games.locator('p:has-text("Collected")').count());
  const internal = await games.locator('.item-card__action:has(button[data-a-target="FGWPOffer"])').elementHandles();
  const external = await games.locator('.item-card__action:has(a[data-a-target="FGWPOffer"])').all();
  internal.reverse();
  external.reverse();
  const sameOrNewPage = async url => new Promise(async (resolve, _reject) => {
    const isNew = page.url() != url;
    let p = page;
    if (isNew) {
      p = await context.newPage();
      await p.goto(url, { waitUntil: 'domcontentloaded' });
    }
    resolve([p, isNew]);
  });
  const skipBasedOnTime = async url => {
    const [p, isNew] = await sameOrNewPage(url);
    const dueDateOrg = await p.locator('.availability-date .tw-bold').innerText();
    const dueDate = new Date(Date.parse(dueDateOrg + ' 17:00'));
    const daysLeft = (dueDate.getTime() - Date.now())/1000/60/60/24;
    console.log(' ', await p.locator('.availability-date').innerText(), '->', daysLeft.toFixed(2));
    if (isNew) await p.close();
    return daysLeft > cfg.pg_timeLeft;
  }
  console.log('\nNumber of free unclaimed games (Prime Gaming):', internal.length);
  for (const card of internal) {
    await card.scrollIntoViewIfNeeded();
    const title = await (await card.$('.item-card-details__body__primary')).innerText();
    const slug = await (await card.$('a')).getAttribute('href');
    const url = 'https://luna.amazon.com' + slug.split('?')[0];
    console.log('Current free game:', chalk.blue(title));
    if (cfg.pg_timeLeft && await skipBasedOnTime(url)) continue;
    if (cfg.dryrun) continue;
    if (cfg.interactive && !await confirm()) continue;
    await (await card.$('.tw-button:has-text("Claim")')).click();
    db.data[user][title] ||= { title, time: datetime(), url, store: 'internal' };
    notify_games.push({ title, status: 'claimed', url });
    await card.screenshot({ path: screenshot('internal', `${filenamify(title)}.png`) });
  }
  console.log('\nNumber of free unclaimed games (external stores):', external.length);
  const external_info = [];
  for (const card of external) {
    const title = await card.locator('.item-card-details__body__primary').innerText();
    const slug = await card.locator('a:has-text("Claim")').first().getAttribute('href');
    const url = 'https://luna.amazon.com' + slug.split('?')[0];
    external_info.push({ title, url });
  }
  for (const { title, url } of external_info) {
    console.log('Current free game:', chalk.blue(title));
    await page.goto(url, { waitUntil: 'domcontentloaded' });
    if (cfg.debug) await page.pause();
    const item_text = await page.innerText('[data-a-target="DescriptionItemDetails"]');
    const store = item_text.toLowerCase().replace(/.* on /, '').slice(0, -1);
    console.log('  External store:', store);
    if (cfg.pg_timeLeft && await skipBasedOnTime(url)) continue;
    if (cfg.dryrun) continue;
    if (cfg.interactive && !await confirm()) continue;
    await page.waitForTimeout(2000);
    const claimBtns = [
      page.click('[data-a-target="buy-box"] .tw-button:has-text("Get game")'),
      page.click('[data-a-target="buy-box"] .tw-button:has-text("Claim")'),
      page.click('.tw-button:has-text("Complete Claim")'),
      page.click('button:has-text("Get game")'),
      page.click('button:has-text("Claim")'),
    ];
    await Promise.any(claimBtns).catch(_ => { console.log('  No claim button found, checking page state...'); });
    await page.waitForTimeout(3000);
    db.data[user][title] ||= { title, time: datetime(), url, store };
    const notify_game = { title, url };
    notify_games.push(notify_game);
    const successIndicators = page.locator('.thank-you-title:has-text("Success"), [data-a-target="success-toast"], text="Successfully claimed"');
    const alreadyClaimed = page.locator('text="Already claimed", text="Collected"');
    if (await successIndicators.count() > 0) {
      console.log('  Successfully claimed!');
    } else if (await alreadyClaimed.count() > 0) {
      console.log('  Already claimed previously.');
    }
    const linkModal = page.locator('[data-a-target="LinkAccountModal"], [data-a-target="LinkAccountButton"]');
    if (await linkModal.count() > 0) {
      console.error('  Account linking is required to claim this offer!');
      notify_game.status = `failed: need account linking for ${store}`;
      db.data[user][title].status = 'failed: need account linking';
    } else {
      db.data[user][title].status = 'claimed';
      const redeem = {
        'gog.com': 'https://www.gog.com/redeem',
        'microsoft store': 'https://account.microsoft.com/billing/redeem',
        xbox: 'https://account.microsoft.com/billing/redeem',
        'legacy games': 'https://www.legacygames.com/primedeal',
      };
      if (store in redeem) {
        const code = await Promise.any([page.inputValue('input[type="text"]'), page.textContent('[data-a-target="ClaimStateClaimCodeContent"]').then(s => s.replace('Your code: ', ''))]);
        console.log('  Code to redeem game:', chalk.blue(code));
        if (store == 'legacy games') {
          redeem[store] = await (await page.$('li:has-text("Click here") a')).getAttribute('href');
        }
        let redeem_url = redeem[store];
        if (store == 'gog.com') redeem_url += '/' + code;
        console.log('  URL to redeem game:', redeem_url);
        db.data[user][title].code = code;
        let redeem_action = 'redeem';
        if (cfg.pg_redeem) {
          console.log(`  Trying to redeem ${code} on ${store} (need to be logged in)!`);
          const page2 = await context.newPage();
          try {
            await page2.goto(redeem[store], { waitUntil: 'domcontentloaded' });
            if (store == 'gog.com') {
              await page2.fill('#codeInput', code);
              const r1 = page2.waitForResponse(r => r.request().method() == 'GET' && r.url().startsWith('https://redeem.gog.com/'));
              await page2.click('[type="submit"]');
              const r1t = await (await r1).text();
              const reason = JSON.parse(r1t).reason;
              if (reason?.includes('captcha')) {
                redeem_action = 'redeem (got captcha)';
                console.error('  Got captcha; could not redeem!');
              } else if (reason == 'code_used') {
                redeem_action = 'already redeemed';
                console.log('  Code was already used!');
              } else if (reason == 'code_not_found') {
                redeem_action = 'redeem (not found)';
                console.error('  Code was not found!');
              } else {
                redeem_action = 'redeemed?';
                console.debug(`  Response 1: ${r1t}`);
                const r2 = page2.waitForResponse(r => r.request().method() == 'POST' && r.url().startsWith('https://redeem.gog.com/'));
                await page2.click('[type="submit"]');
                const r2t = await (await r2).text();
                const reason2 = JSON.parse(r2t).reason;
                if (r2t == '{}') {
                  redeem_action = 'redeemed';
                  console.log('  Redeemed successfully.');
                  db.data[user][title].status = 'claimed and redeemed';
                } else if (reason2?.includes('captcha')) {
                  redeem_action = 'redeem (got captcha)';
                  console.error('  Got captcha; could not redeem!');
                } else {
                  console.debug(`  Response 2: ${r2t}`);
                  console.log('  Unknown response - please check.');
                }
              }
            } else if (store == 'microsoft store' || store == 'xbox') {
              console.error(`  Redeem on ${store} is experimental!`);
              if (page2.url().startsWith('https://login.')) {
                console.error('  Not logged in! Please redeem the code above manually. You can now login in the browser for next time. Waiting for 60s.');
                await page2.waitForTimeout(60 * 1000);
                redeem_action = 'redeem (login)';
              } else {
                const iframe = page2.frameLocator('#redeem-iframe');
                const input = iframe.locator('[name=tokenString]');
                await input.waitFor();
                await input.fill(code);
                const r = page2.waitForResponse(r => r.url().startsWith('https://cart.production.store-web.dynamics.com/v1.0/Redeem/PrepareRedeem'));
                const rt = await (await r).text();
                const j = JSON.parse(rt);
                const reason = j?.events?.cart.length && j.events.cart[0]?.data?.reason;
                if (reason == 'TokenNotFound') {
                  redeem_action = 'redeem (not found)';
                  console.error('  Code was not found!');
                } else if (j?.productInfos?.length && j.productInfos[0]?.redeemable) {
                  await iframe.locator('button:has-text("Next")').click();
                  await iframe.locator('button:has-text("Confirm")').click();
                  const r = page2.waitForResponse(r => r.url().startsWith('https://cart.production.store-web.dynamics.com/v1.0/Redeem/RedeemToken'));
                  const j = JSON.parse(await (await r).text());
                  if (j?.events?.cart.length && j.events.cart[0]?.data?.reason == 'UserAlreadyOwnsContent') {
                    redeem_action = 'already redeemed';
                    console.error('  error: UserAlreadyOwnsContent');
                  } else {
                    redeem_action = 'redeemed';
                    db.data[user][title].status = 'claimed and redeemed?';
                    console.log('  Redeemed successfully?');
                  }
                } else {
                  redeem_action = 'unknown';
                  console.debug(`  Response: ${rt}`);
                  console.log('  Unknown response - please check.');
                }
              }
            } else if (store == 'legacy games') {
              await page2.fill('[name=coupon_code]', code);
              await page2.fill('[name=email]', cfg.lg_email);
              await page2.fill('[name=email_validate]', cfg.lg_email);
              await page2.uncheck('[name=newsletter_sub]');
              await page2.click('[type="submit"]');
              try {
                await page2.waitForSelector('h2:has-text("Thanks for redeeming")');
                redeem_action = 'redeemed';
                db.data[user][title].status = 'claimed and redeemed';
              } catch (error) {
                console.error('  Got error', error);
                redeem_action = 'redeemed?';
                db.data[user][title].status = 'claimed and redeemed?';
              }
            } else {
              console.error(`  Redeem on ${store} not yet implemented!`);
            }
            if (cfg.debug) await page2.pause();
          } catch (redeemError) {
            console.error(`  Auto-redeem failed for ${store}: ${redeemError.message?.split('\n')[0]}`);
            redeem_action = 'redeem (error)';
          } finally {
            await page2.close();
          }
        }
        notify_game.status = `<a href="${redeem_url}">${redeem_action}</a> ${code} on ${store}`;
      } else {
        notify_game.status = `claimed on ${store}`;
        db.data[user][title].status = 'claimed';
      }
      await page.screenshot({ path: screenshot('external', `${filenamify(title)}.png`), fullPage: true });
    }
  }
  await page.goto(URL_CLAIM, { waitUntil: 'domcontentloaded' });
  await page.click('button[data-type="Game"]');

  if (notify_games.length) {
    const p = screenshot(`${filenamify(datetime())}.png`);
    await scrollUntilStable(() => games.locator('.item-card__action').count());
    const viewportSize = page.viewportSize();
    await page.setViewportSize({ ...viewportSize, height: 3000 });
    await games.screenshot({ path: p });
  }

  if (cfg.pg_claimdlc) {
    console.log('Trying to claim in-game content...');
    await page.click('button[data-type="InGameLoot"]');
    const loot = page.locator('div[data-a-target="offer-list-IN_GAME_LOOT"]');
    await loot.waitFor();

    process.stdout.write('Loading all DLCs on page...');
    await scrollUntilStable(() => loot.locator('[data-a-target="item-card"]').count())

    console.log('\nNumber of already claimed DLC:', await loot.locator('p:has-text("Collected")').count());

    const cards = await loot.locator('[data-a-target="item-card"]:has(p:text-is("Claim"))').all();
    console.log('Number of unclaimed DLC:', cards.length);
    const dlcs = await Promise.all(cards.map(async card => ({
      game: await card.locator('.item-card-details__body p').innerText(),
      title: await card.locator('.item-card-details__body__primary').innerText(),
      url: 'https://luna.amazon.com' + await card.locator('a').first().getAttribute('href'),
    })));

    const dlc_unlinked = {};
    for (const dlc of dlcs) {
      const title = `${dlc.game} - ${dlc.title}`;
      const url = dlc.url;
      console.log('Current DLC:', title);
      if (cfg.debug) await page.pause();
      if (cfg.dryrun) continue;
      if (cfg.interactive && !await confirm()) continue;
      db.data[user][title] ||= { title, time: datetime(), store: 'DLC', status: 'failed: need account linking' };
      const notify_game = { title, url };
      notify_games.push(notify_game);
      try {
        await page.goto(url, { waitUntil: 'domcontentloaded' });
        await Promise.any([page.click('.tw-button:has-text("Get in-game content")'), page.click('.tw-button:has-text("Claim your gift")'), page.click('.tw-button:has-text("Claim")').then(() => page.click('button:has-text("Continue")'))]);
        page.click('button:has-text("Continue")').catch(_ => { });
        const linkAccountButton = page.locator('[data-a-target="LinkAccountButton"]');
        let unlinked_store;
        if (await linkAccountButton.count()) {
          unlinked_store = await linkAccountButton.first().getAttribute('aria-label');
          console.debug('  LinkAccountButton label:', unlinked_store);
          const match = unlinked_store.match(/Link (.*) account/);
          if (match && match.length == 2) unlinked_store = match[1];
        } else if (await page.locator('[data-a-target="LinkAccountModal"]').count()) {
          console.error('  Missing account linking:', await page.locator('button[data-a-target="gms-cta"]').innerText().catch(_ => 'unknown'));
          unlinked_store = 'epic-games';
        }
        if (unlinked_store) {
          console.error('  Missing account linking:', unlinked_store, url);
          dlc_unlinked[unlinked_store] ??= [];
          dlc_unlinked[unlinked_store].push(title);
        } else {
          const code = await page.inputValue('input[type="text"]').catch(_ => undefined);
          console.log('  Code to redeem game:', chalk.blue(code));
          db.data[user][title].code = code;
          db.data[user][title].status = 'claimed';
        }
      } catch (error) {
        console.error(error);
      } finally {
        await page.goto(URL_CLAIM, { waitUntil: 'domcontentloaded' });
        await page.click('button[data-type="InGameLoot"]');
      }
    }
    console.log('DLC: Unlinked accounts:', dlc_unlinked);
  }
} catch (error) {
  process.exitCode ||= 1;
  console.error('--- Exception:');
  console.error(error);
  if (error.message && process.exitCode != 130) await notify(`prime-gaming failed: ${error.message.split('\n')[0]}`);
} finally {
  await db.write();
  if (notify_games.length) {
    await notify(`prime-gaming (${user}):<br>${html_game_list(notify_games)}`);
  }
}
if (page.video()) console.log('Recorded video:', await page.video().path());
await context.close();
